//
//  WeatherAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef WeatherAPI_Configuration_h
#define WeatherAPI_Configuration_h

/** The base Uri for API calls */
extern NSString* Configuration_BaseUri;

/** extern reference to the config variable Key */
extern NSString* Configuration_Key;

#endif
