//
//  WeatherAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "Configuration.h"

/** The base Uri for API calls */
NSString* Configuration_BaseUri = @"https://api.weatherapi.com/v1";

/** Replace the value of Key with an appropriate value */
NSString* Configuration_Key = @"";

