//
//  WeatherAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "JSONValueTransformer+NSDate.h"
#import "NSDate+extension.h"
@implementation JSONValueTransformer (NSDate)

-(NSDate*) NSDateFromNSString:(NSString*)string
{
    return [NSDate NSDateFromNSString:string];
}

@end
