//
//  WeatherAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "JSONValueTransformer.h"

@interface JSONValueTransformer (NSDate)

-(NSDate*) NSDateFromNSString:(NSString*)string;

@end
