//
//  WeatherAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_ASTRO
#define APIMATIC_ASTRO

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol Astro
@end

@interface Astro : JSONModel

/**
* Sunrise time
*/
@property NSString* sunrise;

/**
* Sunset time
*/
@property NSString* sunset;

/**
* Moonrise time
*/
@property NSString* moonrise;

/**
* Moonset time
*/
@property NSString* moonset;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif