//
//  WeatherAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "Astro.h"

@implementation Astro

/**
* Sunrise time
*/
@synthesize sunrise;

/**
* Sunset time
*/
@synthesize sunset;

/**
* Moonrise time
*/
@synthesize moonrise;

/**
* Moonset time
*/
@synthesize moonset;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"sunrise": @"sunrise",
        @"sunset": @"sunset",
        @"moonrise": @"moonrise",
        @"moonset": @"moonset"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end