//
//  WeatherAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_CURRENT
#define APIMATIC_CURRENT

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "Condition.h"


//protocol defined for deserialization of JSON
@protocol Current
@end

@interface Current : JSONModel

/**
* Local time when the real time data was updated in unix time.
*/
@property NSNumber* lastUpdatedEpoch;

/**
* Local time when the real time data was updated.
*/
@property NSString* lastUpdated;

/**
* Temperature in celsius
*/
@property NSNumber* tempC;

/**
* Temperature in fahrenheit
*/
@property NSNumber* tempF;

/**
* 1 = Yes 0 = No <br />Whether to show day condition icon or night icon
*/
@property NSNumber* isDay;

/**
* TODO: Write general description for this field
*/
@property Condition* condition;

/**
* Wind speed in miles per hour
*/
@property NSNumber* windMph;

/**
* Wind speed in kilometer per hour
*/
@property NSNumber* windKph;

/**
* Wind direction in degrees
*/
@property NSNumber* windDegree;

/**
* Wind direction as 16 point compass. e.g.: NSW
*/
@property NSString* windDir;

/**
* Pressure in millibars
*/
@property NSNumber* pressureMb;

/**
* Pressure in inches
*/
@property NSNumber* pressureIn;

/**
* Precipitation amount in millimeters
*/
@property NSNumber* precipMm;

/**
* Precipitation amount in inches
*/
@property NSNumber* precipIn;

/**
* Humidity as percentage
*/
@property NSNumber* humidity;

/**
* Cloud cover as percentage
*/
@property NSNumber* cloud;

/**
* Feels like temperature as celcius
*/
@property NSNumber* feelslikeC;

/**
* Feels like temperature as fahrenheit
*/
@property NSNumber* feelslikeF;

/**
* TODO: Write general description for this field
*/
@property NSNumber* visKm;

/**
* TODO: Write general description for this field
*/
@property NSNumber* visMiles;

/**
* UV Index
*/
@property NSNumber* uv;

/**
* Wind gust in miles per hour
*/
@property NSNumber* gustMph;

/**
* Wind gust in kilometer per hour
*/
@property NSNumber* gustKph;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif