//
//  WeatherAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_DAY
#define APIMATIC_DAY

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "Condition.h"


//protocol defined for deserialization of JSON
@protocol Day
@end

@interface Day : JSONModel

/**
* Maximum temperature in celsius for the day.
*/
@property NSNumber* maxtempC;

/**
* Maximum temperature in fahrenheit for the day
*/
@property NSNumber* maxtempF;

/**
* Minimum temperature in celsius for the day
*/
@property NSNumber* mintempC;

/**
* Minimum temperature in fahrenheit for the day
*/
@property NSNumber* mintempF;

/**
* Average temperature in celsius for the day
*/
@property NSNumber* avgtempC;

/**
* Average temperature in fahrenheit for the day
*/
@property NSNumber* avgtempF;

/**
* Maximum wind speed in miles per hour
*/
@property NSNumber* maxwindMph;

/**
* Maximum wind speed in kilometer per hour
*/
@property NSNumber* maxwindKph;

/**
* Total precipitation in milimeter
*/
@property NSNumber* totalprecipMm;

/**
* Total precipitation in inches
*/
@property NSNumber* totalprecipIn;

/**
* Average visibility in kilometer
*/
@property NSNumber* avgvisKm;

/**
* Average visibility in miles
*/
@property NSNumber* avgvisMiles;

/**
* Average humidity as percentage
*/
@property NSNumber* avghumidity;

/**
* TODO: Write general description for this field
*/
@property Condition* condition;

/**
* UV Index
*/
@property NSNumber* uv;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif