//
//  WeatherAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "Forecastday.h"

@implementation Forecastday

/**
* Forecast date
*/
@synthesize date;

/**
* Forecast date as unix time.
*/
@synthesize dateEpoch;

/**
* See day element
*/
@synthesize day;

/**
* TODO: Write general description for this method
*/
@synthesize astro;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"date": @"date",
        @"date_epoch": @"dateEpoch",
        @"day": @"day",
        @"astro": @"astro"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end