//
//  WeatherAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_IPJSONRESPONSE
#define APIMATIC_IPJSONRESPONSE

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol IpJsonResponse
@end

@interface IpJsonResponse : JSONModel

/**
* IP address
*/
@property NSString* ip;

/**
* ipv4 or ipv6
*/
@property NSString* type;

/**
* Continent code
*/
@property NSString* continentCode;

/**
* Continent name
*/
@property NSString* continentName;

/**
* Country code
*/
@property NSString* countryCode;

/**
* Name of country
*/
@property NSString* countryName;

/**
* true or false
*/
@property NSNumber* isEu;

/**
* Geoname ID
*/
@property NSNumber* geonameId;

/**
* City name
*/
@property NSString* city;

/**
* Region name
*/
@property NSString* region;

/**
* Latitude in decimal degree
*/
@property NSNumber* lat;

/**
* Longitude in decimal degree
*/
@property NSNumber* lon;

/**
* Time zone
*/
@property NSString* tzId;

/**
* Local time as epoch
*/
@property NSNumber* localtimeEpoch;

/**
* Date and time
*/
@property NSString* localtime;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif