//
//  WeatherAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "Location.h"

@implementation Location

/**
* Local area name.
*/
@synthesize name;

/**
* Local area region.
*/
@synthesize region;

/**
* Country
*/
@synthesize country;

/**
* Area latitude
*/
@synthesize lat;

/**
* Area longitude
*/
@synthesize lon;

/**
* Time zone
*/
@synthesize tzId;

/**
* Local date and time in unix time
*/
@synthesize localtimeEpoch;

/**
* Local date and time
*/
@synthesize localtime;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"name": @"name",
        @"region": @"region",
        @"country": @"country",
        @"lat": @"lat",
        @"lon": @"lon",
        @"tz_id": @"tzId",
        @"localtime_epoch": @"localtimeEpoch",
        @"localtime": @"localtime"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end