//
//  WeatherAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_SEARCHJSONRESPONSE
#define APIMATIC_SEARCHJSONRESPONSE

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol SearchJsonResponse
@end

@interface SearchJsonResponse : JSONModel

/**
* TODO: Write general description for this field
*/
@property NSNumber* mid;

/**
* Local area name.
*/
@property NSString* name;

/**
* Local area region.
*/
@property NSString* region;

/**
* Country
*/
@property NSString* country;

/**
* Area latitude
*/
@property NSNumber* lat;

/**
* Area longitude
*/
@property NSNumber* lon;

/**
* TODO: Write general description for this field
*/
@property NSString* url;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif