//
//  WeatherAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_TIMEZONEJSONRESPONSE
#define APIMATIC_TIMEZONEJSONRESPONSE

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol TimezoneJsonResponse
@end

@interface TimezoneJsonResponse : JSONModel

/**
* Local area name.
*/
@property NSString* name;

/**
* Local area region.
*/
@property NSString* region;

/**
* Country
*/
@property NSString* country;

/**
* Area latitude
*/
@property NSNumber* lat;

/**
* Area longitude
*/
@property NSNumber* lon;

/**
* Time zone
*/
@property NSString* tzId;

/**
* Local date and time in unix time
*/
@property NSNumber* localtimeEpoch;

/**
* Local date and time
*/
@property NSString* localtime;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif